### PR TITLE
Fix the build on FreeBSD (and OpenBSD?)

### LINKED ISSUE #115: OpenBSD / FreeBSD Support for Subprocess
**Describe the bug**
Building swift-subprocess on OpenBSD fails in `Subprocess+Linux.swift` (and there is no other `spawn` implementation in `Subprocess+Unix.swift`).

**To Reproduce**
1. `swift build` on OpenBSD.

**Expected behavior**
Package builds.

**Environment (please complete the following information):**
 - OpenBSD
 - Swift 6.2/HEAD-ish.

**Additional context**

```
/tmp/swift-subprocess/Sources/Subprocess/Platforms/Subprocess+Linux.swift:373:39: error: value of type 'siginfo_t' has no member 'si_pid'
371 |                 errno = 0
372 |                 if waitid(P_ALL, id_t(0), &siginfo, WEXITED | WNOWAIT) == 0 {
373 |                     let pid = siginfo.si_pid
    |                                       `- error: value of type 'siginfo_t' has no member 'si_pid'
```

This is because for whatever reason, `siginfo_t` on this platform has some internal fields that may be undergoing change and reference to `si_pid` is `#defined` as the internal field path, i.e., `_data._proc._pid`. Of course, Swift doesn't know how to paste those tokens together when importing macros from C.

We probably want some C shims for the platform or something.

As to not lose context, I'm just making note of this right now since it's not in the critical path, but might be in the future, otherwise I'd just dabble with this and fix it myself. (Feel free to assign it to me if you'd like.)

### PR DESCRIPTION
**Pull request by jakepetroules**
For now, we use Dispatch for AsyncIO and process termination monitoring, since BSDs (including macOS) all use kqueue as the Dispatch backend anyways.

This likely also fixes the build on OpenBSD, but I haven't been able to verify that.

Closes #115

### CODE REVIEW

**Comment by jakepetroules** [comment]
@3405691582 does this build on OpenBSD?

File: Sources/Subprocess/Buffer.swift [hunk 1]
```diff
@@ -120,5 +120,45 @@ extension DispatchData.Region {
         }
     }
 }
-#endif
+#if !canImport(Darwin)
```
Comment (iCharlesHu) [inline Sources/Subprocess/Buffer.swift]: Actually, can you make this available on Darwin and BSD? As it turns out, `DispatchData.Region` is defined by `Foundation`, not `Dispatch`, which means we can't use it directly because this package sits below `Foundation`.

This would also close https://github.com/swiftlang/swift-subprocess/issues/129

**Comment by 3405691582** [comment]
Some of the changes discussed on #115 are still missing, so with just the patch atop HEAD it doesn't build. If I apply those changes, namely those below, it seems to build:
* Sources/Subprocess/Platforms/Subprocess+Linux.swift needs to expose the extension and [these changes](https://github.com/swiftlang/swift-subprocess/issues/115#issuecomment-3036878054)
* Sources/Subprocess/Platforms/Subprocess+Unix.swift: the snprintf shim change
* Sources/_SubprocessCShims/include/process_shims.h: snprintf shim needs TARGET_OS_UNIX
* Sources/_SubprocessCShims/process_shims.c: snprintf shim needs TARGET_OS_UNIX
* Tests/SubprocessTests/ProcessMonitoringTests.swift: `testInvalidProcessIdentifier` needs an `os(OpenBSD)`; in `testDoesNotReapUnrelatedChildProcess` the `si_status` extension doesn't seem to be active and I don't know why at the moment.

I tried to run the tests but ran into some other unrelated issues.

File: Sources/Subprocess/Buffer.swift (hunk 1 above)
Comment (jakepetroules) [reply Sources/Subprocess/Buffer.swift]: Sure, although I'm a little confused why the CI is not catching that.

Comment (iCharlesHu) [reply Sources/Subprocess/Buffer.swift]: We have `SubprocessFoundation` trait enabled by default which will get us `DispatchData.Region`. This is only an issue if you specifically turn off `SubprocessFoundation`.

Comment (jakepetroules) [reply Sources/Subprocess/Buffer.swift]: I split that out into #154

File: Sources/Subprocess/IO/AsyncIO+Linux.swift [hunk 2]
```diff
@@ -266,6 +266,11 @@ final class AsyncIO: Sendable {
                     targetEvent = EPOLL_EVENTS(EPOLLOUT)
                 }
 
+                // Save the continuation (before calling epoll_ctl, so we don't miss any data)
+                _registration.withLock { storage in
```
Comment (iCharlesHu) [inline Sources/Subprocess/IO/AsyncIO+Linux.swift:270]: Can you elaborate a bit more on why this change is needed?

File: Sources/Subprocess/Platforms/Subprocess+Unix.swift [hunk 3]
```diff
@@ -411,4 +411,373 @@ extension FileDescriptor {
...
+        try _blockingReap(pid: value)
+    }
+
+    /// Reaps the zombie for the exited process, or returns `nil` if the process is still running. This function will not block.
+    internal func reap() throws(SubprocessError.UnderlyingError) -> TerminationStatus? {
+        try _reap(pid: value)
+    }
+}
+
+@available(*, noasync)
```
Comment (iCharlesHu) [inline Sources/Subprocess/Platforms/Subprocess+Unix.swift:717]: Just curious, what's this for?

**Review by iCharlesHu — APPROVED** [review]

File: Sources/Subprocess/Platforms/Subprocess+Unix.swift (hunk 3 above)
Comment (jakepetroules) [reply Sources/Subprocess/Platforms/Subprocess+Unix.swift:717]: Semantically labels it as blocking -- you'll get an error if you accidentally try to call it in an `async` context.

File: Sources/Subprocess/IO/AsyncIO+Linux.swift (hunk 2 above)
Comment (jakepetroules) [reply Sources/Subprocess/IO/AsyncIO+Linux.swift:270]: There's two threads:
- thread A: thread that calls `registerFileDescriptor`
- thread B: monitor loop

With the original code, the following ordering could occur:
- (thread A) add file descriptor N to epoll
- (thread B) process event for N
- (thread B) look up continuation <-- continuation is nil!
- (thread A) save continuation <-- too late

This change forces the ordering to become:
- (thread A) save continuation
- (thread A) add file descriptor N to epoll
- (thread B) process event for N
- (thread B) look up continuation <-- continuation cannot be nil
