### PR TITLE
Don't suspend/resume the thread while holding an exclusive inout reference

### LINKED ISSUE #182: Swift Subprocess hangs in release builds but works in debug builds
**Describe the bug**

Swift Subprocess library hangs indefinitely when built in release configuration, while working correctly in debug configuration. The `Subprocess.run()` call never completes when running a simple `ls` command in release builds.

**To Reproduce**
What executable was running? `ls`
2. What arguments are passed in? No arguments (just `ls`)
3. What environment values are used? Default environment

Code example:
```swift
let result = try await Subprocess.run(.name("ls"), output: .string(limit: 4096))
```

I reproduced this issue here: https://github.com/kattouf/swift-subprocess-hang-report

**Expected behavior**
The `Subprocess.run()` call should complete successfully and return the process result with output, process identifier, and termination status.

**Environment (please complete the following information):**
 - OS macOS - 15
 - Swift version - swift-driver version: 1.120.5 Apple Swift version 6.1.2 (swiftlang-6.1.2.1.2 clang-1700.0.13.5)
Target: arm64-apple-macosx15.0

**Additional context**
I reproduced this issue with both release 0.1.0 and the main branch.

### PR DESCRIPTION
**Pull request by jakepetroules**
We pass WorkQueue.queue 'by reference' through inout parameters and across thread suspension points. We noticed a stale value issue in release builds when passing Array with inout, likely due to the copy-on-write mechanism. To avoid stale values after a thread resumes from suspension, sleep the worker thread only after releasing the exclusive inout reference, and re-obtain it after resuming.

Resolves #182

### CODE REVIEW

**Comment by jakepetroules** [comment]
This is a more targeted alternative to #194

File: Sources/Subprocess/Platforms/Subprocess+Windows.swift [hunk 1]
```diff
@@ -155,7 +155,7 @@ extension Configuration {
                                         spawnContext.startupInfo.pointer(to: \.StartupInfo)!,
                                         &processInfo
                                     )
-                                    return (result, processInfo, GetLastError())
+                                    return (result, processInfo, result ? ERROR_SUCCESS : GetLastError())
```
Comment (jakepetroules) [inline Sources/Subprocess/Platforms/Subprocess+Windows.swift]: Most Windows functions do NOT set GetLastError to 0 on success (and the CreateProcessW docs don't seem to indicate that it is one), so we need to ensure we aren't getting false positive failures, which I saw regularly in release mode.

File: Sources/Subprocess/Thread.swift [hunk 2]
```diff
@@ -114,20 +115,22 @@ private final class WorkQueue: Sendable {
             pthread_mutex_unlock(mutex)
         }
         #endif
+        if condition(&queue) {
+            #if canImport(WinSDK)
+            SleepConditionVariableCS(self.waitCondition, mutex, INFINITE)
+            #else
+            pthread_cond_wait(self.waitCondition, mutex)
```
Comment (weissi) [inline Sources/Subprocess/Thread.swift:122]: This doesn't look right. `pthread_cont_wait` and pretty much all other low-level condition variable implementations I have used can wake up spuriously. So usually they need to be in a loop. I.e. `while condition(&queue) {` instead of `if condition(&queue)`

Comment (jakepetroules) [reply Sources/Subprocess/Thread.swift:122]: I don't think that alone would be correct in this particular case. If I change this to `while`, it'll hang during shutdown(), because shutdown() clears the queue (making it empty) and then wakes the condition variable. It must proceed in that case rather than go back to sleep.

That said, I think you may be right that something is generally amiss because where dequeue() is called it looks like it could end up terminating the work queue early if the condition variable was woken spuriously, since returning nil can't distinguish "no work items right now" versus "entered shutdown mode".

Comment (weissi) [reply Sources/Subprocess/Thread.swift:122]: Yeah, that doesn't seem good. Condition variables without a `while` are almost never right.

And yes, you'll need to add some sentinel to distinguish shutdown vs. empty
