### PR TITLE
Ensure monitorProcessTermination is ALWAYS called after body runs

### LINKED ISSUE #89: Subprocess.run can hang if body throws
This is a regression introduced by #88. We need to ensure monitorProcessTermination is ALWAYS called after body runs, regardless of whether it threw an error or not.

### PR DESCRIPTION
**Pull request by jakepetroules**
This fixes a regression introduced by #88. We need to ensure monitorProcessTermination is ALWAYS called after body runs, regardless of whether it threw an error or not.

Closes #89

### CODE REVIEW

File: Sources/Subprocess/Configuration.swift [hunk 1]
```diff
@@ -779,15 +788,15 @@ internal func withAsyncTaskCleanupHandler<Result>(
             // so _immediately_ if the failure scenario is due to parent task
             // cancellation. We do so in a detached Task to prevent cancellation
             // of the parent task from interrupting enumeration of the stream itself.
-            await Task.detached {
+            await withUncancelledTask {
```
Comment (jakepetroules) [inline Sources/Subprocess/Configuration.swift:791]: Already had an abstraction for this
